### ISSUE TITLE
Change between front and back camera in runtime?

### ISSUE THREAD

**Issue by fukhaos** [shin10/Starling-WebcamVideo#2]
How I change between front and back camera in runtime?
Thanks by your great work and all help!

**Comment by shin10** [comment]
Hi, I added a setCamera() function to change the camera and (optional the cropping rectangle). It should stop the recording and automatically resume after changing the camera feed. I hope it works, but currently I have no time to test it. I hope it works. Actually I'm not sure whether it's possible on mobile to access both cameras simultaneously ... Let me know if it works or if you encounter any problems and I'll take a look at it the next days.

Cheers. :)

**Comment by fukhaos** [comment]
works fine !!!
thanks !
